### ISSUE TITLE
image size

### ISSUE THREAD

**Issue by liweigu** [PacktPublishing/Java-Machine-Learning-for-Computer-Vision#1]
It seems that the images are resized to 96 x 96, which might bring down the accuracy.
Could you open a parameter for setting image size?

**Comment by klevis** [comment]
@liweigu Although resizing can indeed bring down accuracy , is very little we can do since the model was trained with 96x96X3 images and it expects the same size also during testing(https://github.com/iwantooxxoox/Keras-OpenFace/blob/master/Keras-openface-convertion.ipynb).

**Comment by liweigu** [comment]
I get it. Thanks~
