### ISSUE TITLE
Additional questions

### ISSUE THREAD

**Issue by dascar5** [PacktPublishing/Java-Machine-Learning-for-Computer-Vision#4]
Just wanted to say, amazing work on this!
I was wondering, how would I go about using pictures for detection instead of videos? I'm fairly new to programming so this is something I wanna try to set up on my college campus for fun.

**Comment by klevis** [comment]
Thanks I am glad you find it useful.
A video it is composed by many frames which are played at certain speed so we can perceived as continues movement. So each frame in the end is just a picture as consequence in the end a video is a just sequence of picture showed at certain frequency. 
If you follow this class actually it produces predicted pictures from a video : https://github.com/PacktPublishing/Java-Machine-Learning-for-Computer-Vision/blob/master/CarTracking/src/main/java/ramo/klevis/ml/tracking/data/ProduceDataFromVideo.java
Additionally you can have a look also at **cropImageWithYolo** : https://github.com/PacktPublishing/Java-Machine-Learning-for-Computer-Vision/blob/master/CarTracking/src/main/java/ramo/klevis/ml/tracking/ImageUtils.java

It is fully possible to feed Frames/Picture to **predictBoundingBoxes** at https://github.com/PacktPublishing/Java-Machine-Learning-for-Computer-Vision/blob/master/CarTracking/src/main/java/ramo/klevis/ml/tracking/yolo/Yolo.java:
