### ISSUE TITLE
Executing the Autonomous Driving application

### ISSUE THREAD

**Issue by owaiskerney** [PacktPublishing/Java-Machine-Learning-for-Computer-Vision#5]
Hi there! I am trying to run the Autonomous Driving application in this project but I can't seem to get it working. The UI to select the model (yolov2 or tinyyolo) and the video file shows up but when I press the 'Start Detection' button,  the execution stays still at "Start detecting *video name*" for several minutes and the detection does not start (the progress bar also disappears after a few seconds)

I am using the following build configuration in the pom.xml for Autonomous Driving:

plugin: org.codehaus.mojo
artifact: exec-maven-plugin
version: 1.6.0
goal: java
main class: ramo.klevis.ml.yolo.RunYolo
         
                    
 My system is a Windows 10 PC which satisfies all requirements displayed in the readme for the project.

**Comment by klevis** [comment]
Hi @owaiskerney what java version are you using(java 8 is required)? Additionally maybe you can show error stack trace if possible so I can see what is happening there.

**Comment by owaiskerney** [comment]
![1](https://user-images.githubusercontent.com/29393718/54853982-59ae3680-4d2c-11e9-9540-b33993cd5f6d.PNG)
![yolo2](https://user-images.githubusercontent.com/29393718/54853983-59ae3680-4d2c-11e9-9ba7-26a492f63603.PNG)

Hi again! Really grateful for the prompt reply! My java version is 1.8.0_144.
As you can see in the picture, nothing happens after the select the model to use and the video and press the "Start Detection" button! The program does not terminate or display any errors in the cli

**Comment by klevis** [comment]
The problem is that you are running application from maven rather than from sources and as consequence it failed to find some internal files which are found in sources. In order to run that way you need to proper package the application. Anyway I pushed a change which will allow you to run that way(mvn exec). Please pull the code and "choose a video" before hit "start video" since application will not be able to find default video in class path when run from mvn.

**Comment by owaiskerney** [comment]
Hi! Just pulled the change and it solved my issue! Really appreciate it, thank you!

**Comment by owaiskerney** [comment]
Hi again @klevis ! I tried cloning and running (using maven) the Autonomous Driving project on a linux machine today and am getting the same issue (only with Yolov2, the tinyYolo works perfectly). Any idea why this could be the case? The log is the same as the one posted above.

If you would recommend running the project from source, could you run me through the IntelliJ configurations required? thank you!
