### ISSUE TITLE
Running the Autonomous Driving application on Linux

### ISSUE THREAD

**Issue by owaiskerney** [PacktPublishing/Java-Machine-Learning-for-Computer-Vision#6]
Hi again @klevis ! I tried cloning and running (using maven) the Autonomous Driving project on a linux machine today and am getting the same issue (only with Yolov2, the tinyYolo works perfectly). Any idea why this could be the case? The log is the same as the one posted in my last issue.

If you would recommend running the project from source, could you run me through the IntelliJ configurations required? thank you!

**Comment by klevis** [comment]
@owaiskerney  this could be due to memory issue real yolo needs more memory...
