### ISSUE TITLE
Could not resolve dependencies for project 

### ISSUE THREAD

**Issue by germal** [PacktPublishing/Java-Machine-Learning-for-Computer-Vision#7]
Hi Klevis !

I am using Eclipse to compile your projects. I can build successfully the "common" and the "NeuralStyleTransfer" projects but the others fail to resolve some dependency ( with common and ComputerVision ). Could you please help ?

![immagine](https://user-images.githubusercontent.com/47027729/55390797-3e1b0b00-5538-11e9-8d3e-18dd3ddfdffc.png)

![immagine](https://user-images.githubusercontent.com/47027729/55390822-48d5a000-5538-11e9-8562-3aa8d2d1170e.png)

![immagine](https://user-images.githubusercontent.com/47027729/55390837-4ffcae00-5538-11e9-9f89-782ef25a53b4.png)

Regards
Germal

**Comment by klevis** [comment]
Hi @germal  did you run a mvn clean install on the very root of the project?

**Comment by germal** [comment]
Hi @klevis , no I didn't and indeed that was I need !
Thank you very much !
