### ISSUE TITLE
Running projects with Eclipse

### ISSUE THREAD

**Issue by germal** [PacktPublishing/Java-Machine-Learning-for-Computer-Vision#8]
Hi Klevis,

After building,  I cannot run the projects : for example from the root of the HandwrittenDigits projects I do Run As->Java application , and it tries to download the MNIST db but fails ( network connection is ok)
In the same way I cannot launch other projects. Please for your kind help .
I'm new to Eclipse and Java tools for building so complex projects, sorry for this basic questions.

![immagine](https://user-images.githubusercontent.com/47027729/55411609-3d996900-5566-11e9-95c5-12184327c118.png)

Thanks
Germal

**Comment by klevis** [comment]
Hi,
I think the problem is with eclipse not configured for lombok . This
article may be useful :
https://www.vogella.com/tutorials/Lombok/article.html
Cheers,
Klevis

**Comment by germal** [comment]
Thank you very very much @klevis , this hint solved my problem with Eclipse and saved my week !
Cheers,
Germal
